In [1]:
import numpy as np
import pandas as pd
import os

os.chdir("/Users/mostafa/project")
df = pd.read_csv('student_depression_dataset.csv')

In [14]:
for i in df:
    print(i,sum(df[i].isnull()))
    print(df[i].unique())

id 0
[     2      8     26 ... 140689 140690 140699]
Gender 0
['Male' 'Female']
Age 0
[33. 24. 31. 28. 25. 29. 30. 27. 19. 20. 23. 18. 21. 22. 34. 32. 26. 39.
 35. 42. 36. 58. 49. 38. 51. 44. 43. 46. 59. 54. 48. 56. 37. 41.]
City 23
['Visakhapatnam' 'Bangalore' 'Srinagar' 'Varanasi' 'Jaipur' 'Pune' 'Thane'
 'Chennai' 'Nagpur' 'Nashik' 'Vadodara' 'Kalyan' 'Rajkot' 'Ahmedabad'
 'Kolkata' 'Mumbai' 'Lucknow' 'Indore' 'Surat' 'Ludhiana' 'Bhopal'
 'Meerut' 'Agra' 'Ghaziabad' 'Hyderabad' 'Vasai-Virar' 'Kanpur' 'Patna'
 'Faridabad' 'Delhi' None 'Mira-Bhayandar']
Academic Pressure 0
[5. 2. 3. 4. 1. 0.]
Work Pressure 0
[0. 5. 2.]
CGPA 0
[ 8.97    5.9     7.03    5.59    8.13    5.7     9.54    8.04    9.79
  8.38    6.1     7.04    8.52    5.64    8.58    6.51    7.25    7.83
  9.93    8.74    6.73    5.57    8.59    7.1     6.08    5.74    9.86
  6.7     6.21    5.87    6.37    9.72    5.88    9.56    6.99    5.24
  9.21    7.85    6.95    5.86    7.92    9.66    8.94    9.71    7.87
  5.6     

In [3]:
#Clean City

city_uni = df["City"].unique()
valid_cities = [
    'Visakhapatnam', 'Bangalore', 'Srinagar', 'Varanasi', 'Jaipur',
    'Pune', 'Thane', 'Chennai', 'Nagpur', 'Nashik', 'Vadodara',
    'Kalyan', 'Rajkot', 'Ahmedabad', 'Kolkata', 'Mumbai', 'Lucknow',
    'Indore', 'Surat', 'Ludhiana', 'Bhopal', 'Meerut', 'Agra',
    'Ghaziabad', 'Hyderabad', 'Vasai-Virar', 'Kanpur', 'Patna',
    'Faridabad', 'Delhi'
]
invalid_cities = []
for i in city_uni:
    if i not in valid_cities:
        invalid_cities.append(i)

fix_invalid_city = invalid_cities.copy()
for i in range(len(fix_invalid_city)):
    fix_invalid_city[i] = None

fix_invalid_city[21] = "Ghaziabad"
fix_invalid_city[6] = "Kalyan"
fix_invalid_city[7] = "Mira-Bhayandar"

for i in range(len(invalid_cities)):
    df.loc[df["City"]==invalid_cities[i],"City"] = fix_invalid_city[i] 


In [4]:
#Clean Profession from wrong data 
"""
pro_uni = df.Profession.unique()
fix_pro_uni = pro_uni.copy()
for i in range(len(fix_pro_uni)):
    fix_pro_uni[i] = fix_pro_uni[i].replace(" ","_")
    fix_pro_uni[i] = fix_pro_uni[i].replace("/","_")
    fix_pro_uni[i] = fix_pro_uni[i].replace("'", "")

for i in range(len(pro_uni)):
    df.loc[df["Profession"]==pro_uni[i],"Profession"] = fix_pro_uni[i] 
"""

# we are gonna use just the student so it's true att all, then you should remove it 

student = df["Profession"]=="Student"
df = df[student]
df = df.drop("Profession", axis=1)


In [5]:
#Clean sleep_duration
sleep_uni = df.loc[:,"Sleep Duration"].unique()
sleep_tru = ['5-6 hours', "'Less than 5 hours'", "'7-8 hours'",
       'More than 8 hours']
comb = []
for i in sleep_uni:
    comb.append(df["Sleep Duration"] == i)
sleepers = (comb[0] | comb[1] |comb[2] | comb[3] )
for i in range(4):
    df.loc[comb[i],"Sleep Duration"] = i
df = df[sleepers]

In [6]:
#Clean Dietary Habit
die_uni = df["Dietary Habits"].unique()
die_uni[0] = "Unhealthy"
die_uni[2] = "Healthy"
for i in range(len(die_uni[0:4])):
    df.loc[df["Dietary Habits"]== die_uni[i],["Dietary Habits"]] = i

die = df["Dietary Habits"]< 3
df= df[die]

In [7]:
#Clean Degree
Degree_uni = df["Degree"].unique()
for i in range(len(Degree_uni)):
    df.loc[df["Degree"]== Degree_uni[i],["Degree"]] = i

In [13]:
#Clean suicidal thoughts
df.loc[df["Have you ever had suicidal thoughts ?"]== "Yes",["Have you ever had suicidal thoughts ?"]] = 1
df.loc[df["Have you ever had suicidal thoughts ?"]== "No",["Have you ever had suicidal thoughts ?"]] = 0

In [9]:
#Clean Financial Stress
Financial_st = df["Financial Stress"].unique()[0:5]
mask = df["Financial Stress"].isin(Financial_st)
df = df[mask]


In [10]:
#Clean Family History of Mental Illness
df.loc[df["Family History of Mental Illness"]== "Yes",["Family History of Mental Illness"]] = 1
df.loc[df["Family History of Mental Illness"]== "No",["Family History of Mental Illness"]] = 0

In [11]:
df

id  Gender   Age           City  Academic Pressure  Work Pressure  \
0           2    Male  33.0  Visakhapatnam                5.0            0.0   
1           8  Female  24.0      Bangalore                2.0            0.0   
2          26    Male  31.0       Srinagar                3.0            0.0   
3          30  Female  28.0       Varanasi                3.0            0.0   
4          32  Female  25.0         Jaipur                4.0            0.0   
...       ...     ...   ...            ...                ...            ...   
27896  140685  Female  27.0          Surat                5.0            0.0   
27897  140686    Male  27.0       Ludhiana                2.0            0.0   
27898  140689    Male  31.0      Faridabad                3.0            0.0   
27899  140690  Female  18.0       Ludhiana                5.0            0.0   
27900  140699    Male  27.0          Patna                4.0            0.0   

       CGPA  Study Satisfaction  Job Satisfaction Sleep Duration  \
0      8.97                 2.0               0.0              0   
1      5.90                 5.0               0.0              0   
2      7.03                 5.0               0.0              1   
3      5.59                 2.0               0.0              2   
4      8.13                 3.0               0.0              0   
...     ...                 ...               ...            ...   
27896  5.75                 5.0               0.0              0   
27897  9.40                 3.0               0.0              1   
27898  6.61                 4.0               0.0              0   
27899  6.88                 2.0               0.0              1   
27900  9.24                 1.0               0.0              1   

      Dietary Habits Degree Have you ever had suicidal thoughts ?  \
0                  2      0                                   Yes   
1                  1      1                                    No   
2                  2      2                                    No   
3                  1      3                                   Yes   
4                  1      4                                   Yes   
...              ...    ...                                   ...   
27896              0      6                                   Yes   
27897              2     11                                    No   
27898              0     17                                    No   
27899              2      6                                   Yes   
27900              2      3                                   Yes   

       Work/Study Hours Financial Stress Family History of Mental Illness  \
0                   3.0              1.0                                0   
1                   3.0              2.0                                1   
2                   9.0              1.0                                1   
3                   4.0              5.0                                1   
4                   1.0              1.0                                0   
...                 ...              ...                              ...   
27896               7.0              1.0                                1   
27897               0.0              3.0                                1   
27898              12.0              2.0                                0   
27899              10.0              5.0                                0   
27900               2.0              3.0                                1   

       Depression  
0               1  
1               0  
2               0  
3               1  
4               0  
...           ...  
27896           0  
27897           0  
27898           0  
27899           1  
27900           1  

[27837 rows x 17 columns]